# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20160322_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='weather2',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
