# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_choice_weather2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='weather2',
        ),
        migrations.AlterField(
            model_name='choice',
            name='lati',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='choice',
            name='long',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='lati',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='long',
            field=models.IntegerField(default=0),
        ),
    ]
